services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"

  geoserver:
    image: docker.osgeo.org/geoserver:2.28.x
    ports:
      - "8080:8080"

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  blackbox:
    image: prom/blackbox-exporter:latest
    ports:
      - "9115:9115"

  grafana:
    image: grafana/grafana-oss:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
      - GF_SECURITY_ALLOW_EMBEDDING=true

  geoapi:
    build:
      context: .
      dockerfile: Dockerfile.geoapi
    ports:
      - "3200:3100"
    depends_on:
      - mongo

volumes:
  grafana-storage:
